language: ruby
#branches:
#  only:
#    - master
matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get install -y mosquitto
        - sudo killall mosquitto
      addons:
        apt:
          update: true
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - mosquitto
#    - os: windows # enable when it starts working correctly
#      language: sh
#      before_install:
#        - choco install openjdk #add mosquitto
#        - export PATH=$PATH:"/C/Program Files/OpenJDK/jdk-11.0.2/bin"
#        - export GRADLE_OPTS=-Dorg.gradle.daemon=false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache
script:
  - ./gradlew CI :wire5:bintrayUpload :wire4:bintrayUpload :wire.core:bintrayUpload :time:bintrayUpload :client:bintrayUpload
