addons:
  homebrew:
    taps: homebrew/cask-versions
    casks:
      - adoptopenjdk8
      - android-sdk
    packages:
      - mosquitto
    update: true
  apt:
    sources:
      - sourceline: ppa:mosquitto-dev/mosquitto-ppa
    packages:
      - mosquitto
      - gconf-service
      - libasound2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libgcc1
      - libgconf-2-4
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk-3-0 l
      - ibnspr4
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libstdc++6
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - ca-certificates
      - fonts-liberation
      - libappindicator1
      - libnss3
      - lsb-release
      - xdg-utils wget
  chrome: stable
matrix:
  include:
    - os: linux
      language: android
      dist: trusty
      before_install:
        # Enable user namespace cloning
        - "sysctl kernel.unprivileged_userns_clone=1"
        - mkdir "$ANDROID_HOME/licenses/"
        - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
    - os: osx
      language: ruby
      osx_image: xcode11.2
      before_install:
        - /usr/libexec/java_home -V
        - java -version
        - which java
        - export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
        - echo $JAVA_HOME
        - export PATH="$PATH:/usr/local/sbin/"
        - export ANDROID_HOME=/usr/local/share/android-sdk
        - export PATH=$ANDROID_HOME/tools:$PATH
        - export PATH=$ANDROID_HOME/platform-tools:$PATH
        - export PATH=$ANDROID_HOME/build-tools/29.0.2:$PATH
        - mkdir "$ANDROID_HOME/licenses/"
        - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
#    - os: windows
#      language: sh
#      before_install:
#        - choco install jdk8 -params 'installdir=c:\\java8'
#        - choco install android-sdk
#        - export JAVA_HOME="/C/java8/"
#        - export ANDROID_HOME="/C/Android/android-sdk"
#        - export PATH=$ANDROID_HOME/tools:$PATH
#        - export PATH=$ANDROID_HOME/platform-tools:$PATH
#        - export PATH=$ANDROID_HOME/build-tools/29.0.2:$PATH
#        - mkdir "$ANDROID_HOME/licenses/"
#        - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
#        - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
#        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
#      before_cache:
#        - rm -rf $HOME/.gradle/
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/wrapper/dists/
cache:
  directories:
    - $HOME/travis/.rvm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/
    - $HOME/Library/Caches/Homebrew
    - $HOME/.android/build-cache
script:
  - ./build.sh

