language: ruby
addons:
  homebrew:
    packages: mosquitto
    update: true
  apt:
    sources:
      - sourceline: ppa:mosquitto-dev/mosquitto-ppa
    packages: mosquitto
matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
    - os: osx
      osx_image: xcode11
      before_install:
        - export PATH="$PATH:/usr/local/sbin/"
#    - os: windows # enable when it starts working correctly
#      language: sh
#      before_install:
#        - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
#        - export PATH=${JAVA_HOME}/bin:${PATH}
#        - choco install jdk8 -params 'installdir=c:\\jdk' -y
#        - choco install openjdk #add mosquitto
#        - export PATH=$PATH:"/C/Program Files/OpenJDK/jdk-11.0.2/bin"
#        - export GRADLE_OPTS=-Dorg.gradle.daemon=false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache
script:
  - ./gradlew lint
  - ./gradlew build -x test #let it build first then run tests and lint so we don't run into socket timeout exceptions
  - ./gradlew allTests

