language: ruby
addons:
  homebrew:
    packages: mosquitto, ccache
    update: true
  apt:
    sources:
      - sourceline: ppa:mosquitto-dev/mosquitto-ppa
    packages: mosquitto
matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk8
    - os: osx
      before_install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
        - export PATH="$PATH:/usr/local/sbin/"
      before_cache:
        - brew cleanup
#    - os: windows # enable when it starts working correctly
#      language: sh
#      before_install:
#        - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
#        - export PATH=${JAVA_HOME}/bin:${PATH}
#        - choco install jdk8 -params 'installdir=c:\\jdk' -y
#        - choco install openjdk #add mosquitto
#        - export PATH=$PATH:"/C/Program Files/OpenJDK/jdk-11.0.2/bin"
#        - export GRADLE_OPTS=-Dorg.gradle.daemon=false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/travis/.rvm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/cache
    - $HOME/Library/Caches/Homebrew
script:
  - ./gradlew check build allTests --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false

