addons:
  homebrew:
    packages:
      - mosquitto
      - android-sdk
    update: true
  apt:
    sources:
      - sourceline: ppa:mosquitto-dev/mosquitto-ppa
    packages: mosquitto
  chrome: stable
matrix:
  include:
    - os: linux
      language: android
      dist: trusty
      before_install:
        - mkdir "$ANDROID_HOME/licenses/"
        - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
    - os: osx
      language: java
      osx_image: xcode11.2
      jdk: openjdk9
      before_install:
        - echo "brew cask install android-sdk"
        - brew cask install android-sdk
        - export PATH="$PATH:/usr/local/sbin/"
        - export ANDROID_HOME=/usr/local/share/android-sdk
        - export PATH=$ANDROID_HOME/tools:$PATH
        - export PATH=$ANDROID_HOME/platform-tools:$PATH
        - export PATH=$ANDROID_HOME/build-tools/29.0.2:$PATH
        - mkdir "$ANDROID_HOME/licenses/"
        - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
        - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/travis/.rvm/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.konan/
    - $HOME/Library/Caches/Homebrew
    - $HOME/.android/build-cache
script:
  - ./build.sh
